### ISSUE TITLE
False positives in adlist.txt

### ISSUE THREAD

**Issue by Iconology** [Levi2288/AdvancedBlockList#2]
I'm not sure if you take inspiration from developerdan's lists. However, both of these lists have legitimate use cases. Other active lists have removed these, though I understand the reasoning behind his choice not to. I just wanted to bring it to your attention; it's probably not something most people will need to be whitelisted but worth considering.

https://blocklist-tools.developerdan.com/entries/search?q=ip-api.com

ipify.org (already in your whitelist)
ip-api.com

Keep up the good work.

**Comment by Levi2288** [comment]
Hmm thanks for the report, as told in the repos readme I don't make the blocklist itself I just scrape them from other sources and put together a massive amount of them. I will keep ip-api.com and other stuff like that (public IP APIs and IP trackers) since they are really commonly used in amateur malware and tracking tools, and yes as you pointed it out too 98% of users will probably not need it in their lifetime, so if you are in that 2% I recommend whitelisting it for yourself but for global security I would keep it out of my whitelist at least for now :D. My blocklist collection is aggressive and not for everyone i made it for my personal use so that is why it might not be suitable for every use.
